### ISSUE TITLE
Developing with BLIS and g++ 8.1 results in compile-time type errors

### ISSUE THREAD

**Issue by jacobgorm** [flame/blis#233]
I get this error when trying to compile with GCC 8.1.0:

blis/include/blis/blis.h: In function ‘dom_t bli_dt_domain(num_t)’:
blis/include/blis/blis.h:4162:14: error: invalid conversion from ‘int’ to ‘dom_t’ [-fpermissive]
  return ( dt & BLIS_DOMAIN_BIT );

I've trying adding a cast to fix this, but there are many similar functions that all require similar fixing, so in the end I had to give up.

**Comment by fgvanzee** [comment]
@jacobgorm Is that the only thing that `gcc` prints as part of its compiler error?

**Comment by jacobgorm** [comment]
Actually blis itself and its tests written C compile fine, the problem is including blis.h from a C++ program. For instance, a one-line c++ program that just includes <blis/blis.h> gives:

$ c++ bad.cpp -I build-haswell/blis/include/
In file included from bad.cpp:1:
build-haswell/blis/include/blis/blis.h: In function ‘num_t bli_dt_proj_to_real(num_t)’:
build-haswell/blis/include/blis/blis.h:4057:14: error: invalid conversion from ‘int’ to ‘num_t’ [-fpermissive]
  return ( dt & ~BLIS_BITVAL_COMPLEX );
         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
build-haswell/blis/include/blis/blis.h: In function ‘num_t bli_dt_proj_to_complex(num_t)’:
build-haswell/blis/include/blis/blis.h:4062:14: error: invalid conversion from ‘int’ to ‘num_t’ [-fpermissive]
  return ( dt & BLIS_BITVAL_COMPLEX );
         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
build-haswell/blis/include/blis/blis.h: In function ‘trans_t bli_extract_trans(trans_t)’:
build-haswell/blis/include/blis/blis.h:4110:17: error: invalid conversion from ‘int’ to ‘trans_t’ [-fpermissive]
  return ( trans & BLIS_TRANS_BIT );
         ~~~~~~~~^~~~~~~~~~~~~~~~~~
build-haswell/blis/include/blis/blis.h: In function ‘conj_t bli_extract_conj(trans_t)’:
build-haswell/blis/include/blis/blis.h:4115:17: error: invalid conversion from ‘int’ to ‘conj_t’ [-fpermissive]
  return ( trans & BLIS_CONJ_BIT );
         ~~~~~~~~^~~~~~~~~~~~~~~~~
build-haswell/blis/include/blis/blis.h: In function ‘trans_t bli_trans_toggled(trans_t)’:
build-haswell/blis/include/blis/blis.h:4120:17: error: invalid conversion from ‘int’ to ‘trans_t’ [-fpermissive]
  return ( trans ^ BLIS_TRANS_BIT );
         ~~~~~~~~^~~~~~~~~~~~~~~~~~
build-haswell/blis/include/blis/blis.h: In function ‘trans_t bli_trans_toggled_conj(trans_t)’:
build-haswell/blis/include/blis/blis.h:4125:17: error: invalid conversion from ‘int’ to ‘trans_t’ [-fpermissive]
  return ( trans ^ BLIS_CONJ_BIT );
         ~~~~~~~~^~~~~~~~~~~~~~~~~
build-haswell/blis/include/blis/blis.h: In function ‘uplo_t bli_uplo_toggled(uplo_t)’:
build-haswell/blis/include/blis/blis.h:4187:41: error: invalid conversion from ‘int’ to ‘uplo_t’ [-fpermissive]
  return ( bli_is_upper_or_lower( uplo ) ?
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
           ( ( uplo ^ BLIS_LOWER_BIT ) ^ BLIS_UPPER_BIT ) : uplo
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         );
         ~                                
build-haswell/blis/include/blis/blis.h: In function ‘conj_t bli_conj_toggled(conj_t)’:
build-haswell/blis/include/blis/blis.h:4241:16: error: invalid conversion from ‘int’ to ‘conj_t’ [-fpermissive]
  return ( conj ^ BLIS_CONJ_BIT );
         ~~~~~~~^~~~~~~~~~~~~~~~~
build-haswell/blis/include/blis/blis.h: In function ‘conj_t bli_apply_conj(conj_t, conj_t)’:
build-haswell/blis/include/blis/blis.h:4246:16: error: invalid conversion from ‘int’ to ‘conj_t’ [-fpermissive]
  return ( conj ^ conjapp );

(...)

**Comment by jacobgorm** [comment]
Btw, I have tried wrapping in extern "C", but that does not help.

**Comment by fgvanzee** [comment]
@jacobgorm Yeah, `blis.h` already supplies the `extern "C"`. This is likely a C++ type issue.

@devinamatthews has more experience with C++. In fact, I recall him informing me that C++ treats `enums` as actual types, whereas C99 simply treats them all indistinguishably as "some integer." Devin, can you decipher what's going on here? Is this something I can fix by adding explicit typecasts? In other words, whereas now we have:
```
static dom_t bli_obj_domain( obj_t* obj )
{
    return ( obj->info & BLIS_DOMAIN_BIT );
}
```
I would change it to:
```
static dom_t bli_obj_domain( obj_t* obj )
{
    return ( ( dom_t )obj->info & ( dom_t )BLIS_DOMAIN_BIT );
}
```

**Comment by jacobgorm** [comment]
@fgvanzee that is the type of fixes I tried, it seems to work, but I did not get to the end of the compile errors (I am happy to share my 630 lines partial patch if that is helpful.)

**Comment by fgvanzee** [comment]
@jacobgorm I appreciate the offer. The problem is, if you are editing the `blis.h` in the error message, you are editing the wrong file. That `blis.h` is generated from the smaller files at compile-time.

If you are editing `frame/include/bli_obj_macro_defs.h`, then you are welcome to share your patch so far and I'll take over. But I don't know how to enable the compiler type behavior you're observing (I only have an older version of `gcc`), so I'm going to count on you to provide feedback as we iterate towards a completely-fixed state.

**Comment by jacobgorm** [comment]
I did the editing in the right places it seems. Ironically, github will not allow me to attach a .patch file created with $ git format-patch, so I have sent the file via email instead.

**Comment by fgvanzee** [comment]
@jacobgorm I received the patch. And thank you for submitting this bug report. I can't guarantee when this will be fixed, but I'll try to prioritize it relatively high. (Maybe later this week?)

Thanks for your patience.

**Comment by jacobgorm** [comment]
No rush, but thanks for looking into this @fgvanzee !

**Comment by devinamatthews** [comment]
@fgvanzee  re:
```C++
static dom_t bli_obj_domain( obj_t* obj )
{
    return ( ( dom_t )obj->info & ( dom_t )BLIS_DOMAIN_BIT );
}
```
That is the right idea, but you should cast after the bitwise operation. C++ actually does allow implicit casting from `enum` to integer types and back, but since you are using `typedef enum ... dom_t` it is treated as an `enum class` (I think?).

**Comment by fgvanzee** [comment]
@devinamatthews So you're suggesting that something like this
```c
static dom_t bli_obj_domain( obj_t* obj )
{
    return ( dom_t )( obj->info & BLIS_DOMAIN_BIT );
}
```
would be necessary? Would it be sufficient (omitting the operand typecasts)?

**Comment by devinamatthews** [comment]
Try it 😃 !

**Comment by fgvanzee** [comment]
@jacobgorm Would you mind confirming that the typecasting above (where we cast only the result and not the operands) is sufficient to placate the compiler? You don't need to try it for every instance represented in the patch you sent--just one or two will suffice.

**Comment by jacobgorm** [comment]
Yes I can confirm that the typecasts are sufficient to make the compiler
happy.

**Comment by fgvanzee** [comment]
@devinamatthews In an attempt to try to recreate some of the errors that @jacobgorm reported here (those that have nothing to do with the version and everything to do with the C++), I tried manually switching my compilation of BLIS to `g++` instead of `gcc`. I have managed to get quite far--the `blis.h` header seems fine now--but when compiling the kernels I got the following error:
```
In file included from kernels/zen/3/bli_gemm_zen_asm_d6x8.c:39:0:
./frame/include/bli_x86_asm_macros.h:653:9: error: "and" cannot be used as a macro name as it is an operator in C++
 #define and(_0, _1) AND(_0, _1)
         ^
compilation terminated due to -Wfatal-errors.
Makefile:540: recipe for target 'obj/haswell/kernels/zen/3/bli_gemm_zen_asm_d6x8.o' failed
```

1. How did you avoid this error in TBLIS?
2. Is there a natural/obvious way around this (as a more permanent solution)?
3. Especially if "no" to (2), what do you suggest I do to at least temporarily get around it?

**Comment by fgvanzee** [comment]
@devinamatthews Nevermind. It occurred to me just now that Jacob's problem is simply including `blis.h` from a C++ application, not building BLIS with C++. So I may be done.

**Comment by fgvanzee** [comment]
@jacobgorm I've just pushed my first commit of fixes. Try b7db293 (head of `dev` branch) and then inform me of any remaining error messages you experience.

**Comment by jacobgorm** [comment]
I can confirm that it compiles and that SGEMM() works on my x86_64 with G++
8.1.0.

Thanks a lot!
Jacob

**Comment by fgvanzee** [comment]
Good to hear, Jacob. I'm going to close this issue. Please let us know if you encounter any other problems while developing with BLIS.
